django_crontab_manager/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

app_name = "django_crontab_manager"

from .views import (
    CronJobHomeView,    
    AddAllCronJobsView,
    AddAllCronJobsAdminView,
    RemoveAllCronJobsView,        
    RemoveAllCronJobsAdminView,
    RunCronJobView,
)

urlpatterns = [
    path("", login_required(CronJobHomeView.as_view()), name="home"),    
    path("add/", login_required(AddAllCronJobsView.as_view()), name="add"),    
    path("add-admin/", login_required(AddAllCronJobsAdminView.as_view()), name="add-admin"),    
    path("remove/", login_required(RemoveAllCronJobsView.as_view()), name="remove"), 
    path("remove-admin/", login_required(RemoveAllCronJobsAdminView.as_view()), name="remove-admin"),        
    path("run/<str:jobhash>/", login_required(RunCronJobView.as_view()), name="run"),
    path("run-admin/<str:jobhash>/", login_required(RunCronJobView.as_view()), name="run"),
]

django_crontab_manager/models.py
from django.db import models

class Cronjob(models.Model):

    class Meta:        
        verbose_name = "Cronjob"        
        verbose_name_plural = 'Cronjobs'

    jobhash = models.SlugField(max_length=50, unique=True, blank=False)
    setting = models.TextField(blank=False)    
    created_at = models.DateTimeField("Created", auto_now_add=True)
    updated_at = models.DateTimeField("Updated", auto_now=True)                           

    def __str__(self) -> str:
        return self.setting

django_crontab_manager/views.py
from django.contrib import messages
from django.shortcuts import Http404, HttpResponseRedirect, redirect, render
from django.urls import reverse
from django.views import View

from django_crontab_manager.adapters import DjangoExecutor
from .services import (
    get_cronjob_from_settings,
    get_cronjob_running,
    run_cronjob,
    add_all_cronjobs,
    remove_all_cronjobs,
)


class CronJobHomeView(View):

    template_name = "django_crontab_manager/home.html"

    def get(self, request, *args, **kwargs):
        view_context = {
            "settings_cronjobs": get_cronjob_from_settings(),
            "running_cronjobs": get_cronjob_running(),
        }
        return render(request, self.template_name, view_context)


class RunCronJobView(View):
    def get(self, request, *args, **kwargs):
        jobhash = self.kwargs.get("jobhash")
        run_cronjob(jobhash, DjangoExecutor())
        messages.success(self.request, f"Running the {jobhash} cronjob")
        return HttpResponseRedirect(reverse("django_crontab_manager:home"))


class RunCronJobAdminView(View):  # pragma: no cover
    """Not in use yet"""

    def get(self, request, *args, **kwargs):
        jobhash = self.kwargs.get("jobhash")
        run_cronjob(jobhash, DjangoExecutor())
        messages.success(self.request, f"Running the {jobhash} cronjob")
        return HttpResponseRedirect(
            reverse("admin:django_crontab_manager_cronjob_changelist")
        )


class AddAllCronJobsView(View):
    def get(self, request, *args, **kwargs):
        add_all_cronjobs(DjangoExecutor())
        messages.success(
            self.request, f"All cronjobs were removed from execution successfully!"
        )
        return HttpResponseRedirect(reverse("django_crontab_manager:home"))


class AddAllCronJobsAdminView(View):
    def get(self, request, *args, **kwargs):
        add_all_cronjobs(DjangoExecutor())
        messages.success(
            self.request, f"All cronjobs were removed from execution successfully!"
        )
        return HttpResponseRedirect(
            reverse("admin:django_crontab_manager_cronjob_changelist")
        )


class RemoveAllCronJobsView(View):
    def get(self, request, *args, **kwargs):
        remove_all_cronjobs(DjangoExecutor())
        messages.success(self.request, f"All cronjobs were removed successfully!")
        return HttpResponseRedirect(reverse("django_crontab_manager:home"))


class RemoveAllCronJobsAdminView(View):
    def get(self, request, *args, **kwargs):
        remove_all_cronjobs(DjangoExecutor())
        messages.success(self.request, f"All cronjobs were removed successfully!")
        return HttpResponseRedirect(
            reverse("admin:django_crontab_manager_cronjob_changelist")
        )

django_crontab_manager/templates/django_crontab_manager/admin_cronjob_change_form.html
{% extends 'admin/change_form.html' %}

{% block submit_buttons_bottom %}
{{ block.super }}
<div class="object-tools">
    <a href="{% url 'django_crontab_manager:remove-admin' %}" 
        class="btn btn-block btn-outline-secondary btn-sm" 
        title="Run the selected action"
        name="index" value="0">Remove All</a>
</div>
{% endblock %}

django_crontab_manager/templates/django_crontab_manager/admin_cronjob_changelist.html
{% extends 'admin/change_list.html' %}
{% block object-tools %}
<div class="actions">
    <a href="{% url 'django_crontab_manager:add-admin' %}" class="btn btn-success" title="Run the selected action" name="index" value="0">Add All to Cron</a>
    <a href="{% url 'django_crontab_manager:remove-admin' %}" class="btn btn-danger" title="Run the selected action" name="index" value="0">Remove All</a>
</div>
<br />
{{ block.super }}   
{% endblock %}

django_crontab_manager/templates/django_crontab_manager/base.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>Pixeon Django Doilerplate</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">    
</head>

<body>
    {% include "django_crontab_manager/header.html" %}    
    <div class="ui main container" style="position: relative;">
        {% if messages %}        
            {% for message in messages %}
                <div class="ui positive message">
                    <i class="close icon"></i>
                    <div class="header">Success!</div>
                    <p>{{ message }}</p>
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
        {% include "django_crontab_manager/footer.html" %}    
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
    <script src="{% static 'base/js/script.js' %}"></script>
</body>

</html>

django_crontab_manager/templates/django_crontab_manager/footer.html
<div class="ui footer"><br></div>

django_crontab_manager/templates/django_crontab_manager/header.html
{% include "django_crontab_manager/navbar.html" %}

django_crontab_manager/templates/django_crontab_manager/home.html
{% extends 'django_crontab_manager/base.html' %}
{% load lookup_dict %}
{% block content %}
<h1 class="ui header">CRONJOBS</h1>
<div class="ui divided items">
    <h4>FROM SETTINGS</h4>
    <table class="ui celled table">
        <thead class="full-width">
            <tr>
                <th>No.</th>
                <th>Job Hash</th>
                <th>Setting</th>                
            </tr>
        </thead>
        <tbody class="full-width">
            {% for jobhash,cronjob in settings_cronjobs.items %}
            <tr>
                <td data-label="no">{{forloop.counter}}</td>
                <td data-label="jobhash">{{jobhash}}</td>
                <td data-label="cronjob"><small>{{cronjob}}</small></td>                
            </tr>
            {% endfor %}
        </tbody>
        <tfoot class="full-width">
            <tr>
                <th></th>
                <th colspan="4">
                    <a href="{% url 'django_crontab_manager:add' %}" class="ui right floated small primary labeled icon button">
                        {% if running_cronjobs %}
                        <i class="caret square right icon"></i>Reload
                        {% else %}
                        <i class="caret square right icon"></i>Run All
                        {% endif %}
                    </a>
                </th>
            </tr>
        </tfoot>
    </table>
</div>

<div class="ui divided items">
    <h4>RUNNING</h4>
    <table class="ui celled table">
        <thead class="full-width">
            <tr>
                <th>No.</th>
                <th>Job Hash</th>
                <th>Setting</th>
                <th>Command</th>
                <th></th>
            </tr>
        </thead>
        <tbody class="full-width">
            {% for jobhash,cronjob in running_cronjobs.items %}
            <tr>
                <td data-label="no">{{forloop.counter}}</td>
                <td data-label="jobhash">{{jobhash}}</td>
                <td data-label="cronjob"><small>{{cronjob|lookup_dict:"setting"}}</small></td>
                <td data-label="cronjob"><small>{{cronjob|lookup_dict:"command"}}</small></td>
                <td data-label="actions">
                    <a href="{% url 'django_crontab_manager:run' jobhash=jobhash %}"
                        class="ui right floated mini positive labeled icon button">
                        <i class="caret square right icon"></i> Execute
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot class="full-width">
            <tr>
                <th></th>
                <th colspan="4">
                    <a href="{% url 'django_crontab_manager:remove' %}" class="ui right floated small negative labeled icon button">
                        <i class="user icon"></i> Remove All
                    </a>
                </th>
            </tr>
        </tfoot>
    </table>
</div>
{% endblock %}

django_crontab_manager/templates/django_crontab_manager/navbar.html
<div class="ui inverted menu">
    <div class="ui container">
        <a href="{% url 'django_crontab_manager:home' %}" class="header item">PIXEON CRONJOBS MANAGER</a>
        <a href="{% url 'admin:django_crontab_manager_cronjob_changelist' %}" class="item"><i class="cog icon"></i>ADMIN</a>        
    </div>
</div>